
import type { StateData } from './heritage-data';
import { monuments } from './monuments-data';
import { cuisine } from './cuisine-data';
import { festivals } from './festivals-data';
import { artForms } from './art-data';

export const indianStates: StateData[] = [
  {
    slug: 'uttar-pradesh',
    name: 'Uttar Pradesh',
    description: 'The heartland of India, rich in history, culture, and spirituality.',
    imageId: 'state-uttar-pradesh',
    monuments: monuments.filter(m => ['Agra Fort', 'Fatehpur Sikri'].includes(m.name)),
    cuisine: cuisine.filter(c => ['Bedmi Puri', 'Petha'].includes(c.name)),
    festivals: festivals.filter(f => ['Diwali', 'Holi'].includes(f.name)),
    artForms: artForms.filter(a => ['Chikankari'].includes(a.name)),
  },
  {
    slug: 'rajasthan',
    name: 'Rajasthan',
    description: 'The land of kings, majestic forts, vibrant culture, and vast deserts.',
    imageId: 'state-rajasthan',
    monuments: monuments.filter(m => ['Hawa Mahal', 'Amer Fort'].includes(m.name)),
    cuisine: cuisine.filter(c => ['Dal Baati Churma', 'Ghevar'].includes(c.name)),
    festivals: festivals.filter(f => ['Pushkar Fair'].includes(f.name)),
    artForms: artForms.filter(a => ['Blue Pottery', 'Kathputli'].includes(a.name)),
  },
  {
    slug: 'karnataka',
    name: 'Karnataka',
    description: 'A blend of ancient heritage, modern technology, and stunning natural beauty.',
    imageId: 'state-karnataka',
    monuments: monuments.filter(m => ['Mysore Palace', 'Gol Gumbaz'].includes(m.name)),
    cuisine: cuisine.filter(c => ['Bisi Bele Bath', 'Mysore Pak'].includes(c.name)),
    festivals: festivals.filter(f => ['Dasara'].includes(f.name)),
    artForms: artForms.filter(a => ['Mysore Painting'].includes(a.name)),
  },
  {
    slug: 'odisha',
    name: 'Odisha',
    description: 'Home to ancient temples, serene beaches, and rich artistic traditions.',
    imageId: 'state-odisha',
    monuments: monuments.filter(m => ['Lingaraja Temple', 'Udayagiri Caves'].includes(m.name)),
    cuisine: cuisine.filter(c => ["Chenna Poda", "Pakhala Bhata"].includes(c.name)),
    festivals: festivals.filter(f => ["Ratha Yatra"].includes(f.name)),
    artForms: artForms.filter(a => ["Pattachitra"].includes(a.name)),
  },
  {
    slug: 'andhra-pradesh',
    name: 'Andhra Pradesh',
    description: 'Known for its rich history, spiritual centers, and spicy cuisine.',
    imageId: 'state-andhra-pradesh',
    monuments: monuments.filter(m => ['Tirupati'].includes(m.name)),
    cuisine: cuisine.filter(c => ['Pulihora'].includes(c.name)),
    festivals: festivals.filter(f => ['Ugadi'].includes(f.name)),
    artForms: artForms.filter(a => ['Kalamkari'].includes(a.name)),
  },
  {
    slug: 'arunachal-pradesh',
    name: 'Arunachal Pradesh',
    description: 'The land of the rising sun, with breathtaking mountains and diverse tribes.',
    imageId: 'state-arunachal-pradesh',
    monuments: monuments.filter(m => ['Tawang Monastery'].includes(m.name)),
    cuisine: cuisine.filter(c => ['Thukpa'].includes(c.name)),
    festivals: festivals.filter(f => ['Losar'].includes(f.name)),
    artForms: artForms.filter(a => ['Apatani Weaving'].includes(a.name)),
  },
  {
    slug: 'assam',
    name: 'Assam',
    description: 'Famous for its tea gardens, rich wildlife, and vibrant culture.',
    imageId: 'state-assam',
    monuments: monuments.filter(m => ['Kamakhya Temple'].includes(m.name)),
    cuisine: cuisine.filter(c => ['Masor Tenga'].includes(c.name)),
    festivals: festivals.filter(f => ['Bihu'].includes(f.name)),
    artForms: artForms.filter(a => ['Muga Silk'].includes(a.name)),
  },
  {
    slug: 'bihar',
    name: 'Bihar',
    description: 'An ancient land of learning and spirituality, home to major historical sites.',
    imageId: 'state-bihar',
    monuments: monuments.filter(m => ['Mahabodhi Temple'].includes(m.name)),
    cuisine: cuisine.filter(c => ['Litti Chokha'].includes(c.name)),
    festivals: festivals.filter(f => ['Chhath Puja'].includes(f.name)),
    artForms: artForms.filter(a => ['Madhubani Painting'].includes(a.name)),
  },
  {
    slug: 'chhattisgarh',
    name: 'Chhattisgarh',
    description: 'A heavily forested state known for its waterfalls, caves, and tribal culture.',
    imageId: 'state-chhattisgarh',
    monuments: monuments.filter(m => ['Chitrakote Falls'].includes(m.name)),
    cuisine: cuisine.filter(c => ['Faraa'].includes(c.name)),
    festivals: festivals.filter(f => ['Bastar Dussehra'].includes(f.name)),
    artForms: artForms.filter(a => ['Dhokra'].includes(a.name)),
  },
  {
    slug: 'goa',
    name: 'Goa',
    description: 'Famous for its pristine beaches, vibrant nightlife, and Portuguese heritage.',
    imageId: 'state-goa',
    monuments: monuments.filter(m => ['Basilica of Bom Jesus'].includes(m.name)),
    cuisine: cuisine.filter(c => ['Goan Fish Curry'].includes(c.name)),
    festivals: festivals.filter(f => ['Goa Carnival'].includes(f.name)),
    artForms: artForms.filter(a => ['Azulejos'].includes(a.name)),
  },
  {
    slug: 'gujarat',
    name: 'Gujarat',
    description: 'A land of diverse landscapes, from deserts to coastlines, with a rich history.',
    imageId: 'state-gujarat',
    monuments: monuments.filter(m => ['Rani ki Vav'].includes(m.name)),
    cuisine: cuisine.filter(c => ['Dhokla'].includes(c.name)),
    festivals: festivals.filter(f => ['Navaratri'].includes(f.name)),
    artForms: artForms.filter(a => ['Bandhani'].includes(a.name)),
  },
  {
    slug: 'haryana',
    name: 'Haryana',
    description: 'An agricultural hub with a rich history dating back to the Vedic period.',
    imageId: 'state-haryana',
    monuments: monuments.filter(m => ['Kurukshetra'].includes(m.name)),
    cuisine: cuisine.filter(c => ['Bajra Khichdi'].includes(c.name)),
    festivals: festivals.filter(f => ['Gugga Naumi'].includes(f.name)),
    artForms: artForms.filter(a => ['Panja Durries'].includes(a.name)),
  },
  {
    slug: 'himachal-pradesh',
    name: 'Himachal Pradesh',
    description: 'A Himalayan paradise with stunning mountain landscapes and adventure sports.',
    imageId: 'state-himachal-pradesh',
    monuments: monuments.filter(m => ['Hadimba Temple'].includes(m.name)),
    cuisine: cuisine.filter(c => ['Dham'].includes(c.name)),
    festivals: festivals.filter(f => ['Kullu Dussehra'].includes(f.name)),
    artForms: artForms.filter(a => ['Kangra Painting'].includes(a.name)),
  },
  {
    slug: 'jharkhand',
    name: 'Jharkhand',
    description: 'A state rich in mineral wealth, dense forests, and vibrant tribal culture.',
    imageId: 'state-jharkhand',
    monuments: monuments.filter(m => ['Baidyanath Temple'].includes(m.name)),
    cuisine: cuisine.filter(c => ['Dhuska'].includes(c.name)),
    festivals: festivals.filter(f => ['Sarhul'].includes(f.name)),
    artForms: artForms.filter(a => ['Sohrai Art'].includes(a.name)),
  },
  {
    slug: 'kerala',
    name: 'Kerala',
    description: "God's Own Country, known for its serene backwaters, lush greenery, and rich traditions.",
    imageId: 'hero-kerala-backwaters',
    monuments: monuments.filter(m => ['Mattancherry Palace'].includes(m.name)),
    cuisine: cuisine.filter(c => ['Appam and Stew'].includes(c.name)),
    festivals: festivals.filter(f => ['Onam'].includes(f.name)),
    artForms: artForms.filter(a => ['Kathakali'].includes(a.name)),
  },
  {
    slug: 'madhya-pradesh',
    name: 'Madhya Pradesh',
    description: 'The heart of India, with ancient temples, national parks, and rich history.',
    imageId: 'state-madhya-pradesh',
    monuments: monuments.filter(m => ['Khajuraho'].includes(m.name)),
    cuisine: cuisine.filter(c => ['Poha-Jalebi'].includes(c.name)),
    festivals: festivals.filter(f => ['Lokrang Festival'].includes(f.name)),
    artForms: artForms.filter(a => ['Gond Painting'].includes(a.name)),
  },
  {
    slug: 'maharashtra',
    name: 'Maharashtra',
    description: 'A state of contrasts, from the bustling metropolis of Mumbai to ancient caves.',
    imageId: 'state-maharashtra',
    monuments: monuments.filter(m => ['Ajanta & Ellora Caves'].includes(m.name)),
    cuisine: cuisine.filter(c => ['Vada Pav'].includes(c.name)),
    festivals: festivals.filter(f => ['Ganesh Chaturthi'].includes(f.name)),
    artForms: artForms.filter(a => ['Warli Painting'].includes(a.name)),
  },
  {
    slug: 'manipur',
    name: 'Manipur',
    description: 'The jewel of India, known for its classical dance, natural beauty, and sports.',
    imageId: 'state-manipur',
    monuments: monuments.filter(m => ['Kangla Fort'].includes(m.name)),
    cuisine: cuisine.filter(c => ['Eromba'].includes(c.name)),
    festivals: festivals.filter(f => ['Sangai Festival'].includes(f.name)),
    artForms: artForms.filter(a => ['Manipuri Dance'].includes(a.name)),
  },
  {
    slug: 'meghalaya',
    name: 'Meghalaya',
    description: 'The abode of clouds, famous for its living root bridges and heavy rainfall.',
    imageId: 'state-meghalaya',
    monuments: monuments.filter(m => ['Living Root Bridges'].includes(m.name)),
    cuisine: cuisine.filter(c => ['Jadoh'].includes(c.name)),
    festivals: festivals.filter(f => ['Wangala'].includes(f.name)),
    artForms: artForms.filter(a => ['Cane and Bamboo Crafts'].includes(a.name)),
  },
  {
    slug: 'mizoram',
    name: 'Mizoram',
    description: 'A land of rolling hills, vibrant culture, and close-knit communities.',
    imageId: 'state-mizoram',
    monuments: monuments.filter(m => ['Vantawng Falls'].includes(m.name)),
    cuisine: cuisine.filter(c => ['Bai'].includes(c.name)),
    festivals: festivals.filter(f => ['Chapchar Kut'].includes(f.name)),
    artForms: artForms.filter(a => ['Puan Weaving'].includes(a.name)),
  },
  {
    slug: 'nagaland',
    name: 'Nagaland',
    description: 'A vibrant hill state, home to diverse indigenous tribes and rich traditions.',
    imageId: 'state-nagaland',
    monuments: monuments.filter(m => ['Kohima War Cemetery'].includes(m.name)),
    cuisine: cuisine.filter(c => ['Axone'].includes(c.name)),
    festivals: festivals.filter(f => ['Hornbill Festival'].includes(f.name)),
    artForms: artForms.filter(a => ['Naga Shawls'].includes(a.name)),
  },
  {
    slug: 'punjab',
    name: 'Punjab',
    description: 'The land of five rivers, known for its fertile fields and vibrant culture.',
    imageId: 'state-punjab',
    monuments: monuments.filter(m => ['Golden Temple'].includes(m.name)),
    cuisine: cuisine.filter(c => ['Makki di Roti & Sarson da Saag'].includes(c.name)),
    festivals: festivals.filter(f => ['Baisakhi'].includes(f.name)),
    artForms: artForms.filter(a => ['Phulkari'].includes(a.name)),
  },
  {
    slug: 'sikkim',
    name: 'Sikkim',
    description: 'A Himalayan wonderland with pristine landscapes and Buddhist monasteries.',
    imageId: 'state-sikkim',
    monuments: monuments.filter(m => ['Rumtek Monastery'].includes(m.name)),
    cuisine: cuisine.filter(c => ['Momos'].includes(c.name)),
    festivals: festivals.filter(f => ['Saga Dawa'].includes(f.name)),
    artForms: artForms.filter(a => ['Thangka Painting'].includes(a.name)),
  },
  {
    slug: 'tamil-nadu',
    name: 'Tamil Nadu',
    description: 'A land of towering temples, classical dance, and a rich literary tradition.',
    imageId: 'state-tamil-nadu',
    monuments: monuments.filter(m => ['Meenakshi Amman Temple'].includes(m.name)),
    cuisine: cuisine.filter(c => ['Pongal'].includes(c.name)),
    festivals: festivals.filter(f => ['Pongal'].includes(f.name)),
    artForms: artForms.filter(a => ['Bharatanatyam'].includes(a.name)),
  },
  {
    slug: 'telangana',
    name: 'Telangana',
    description: 'A historic region, home to iconic monuments and a unique Deccan culture.',
    imageId: 'state-telangana',
    monuments: monuments.filter(m => ['Charminar'].includes(m.name)),
    cuisine: cuisine.filter(c => ['Hyderabadi Biryani'].includes(c.name)),
    festivals: festivals.filter(f => ['Bathukamma'].includes(f.name)),
    artForms: artForms.filter(a => ['Bidriware'].includes(a.name)),
  },
  {
    slug: 'tripura',
    name: 'Tripura',
    description: 'A hilly state with a rich cultural heritage, palaces, and bamboo crafts.',
    imageId: 'state-tripura',
    monuments: monuments.filter(m => ['Ujjayanta Palace'].includes(m.name)),
    cuisine: cuisine.filter(c => ['Chauk'].includes(c.name)),
    festivals: festivals.filter(f => ['Kharchi Puja'].includes(f.name)),
    artForms: artForms.filter(a => ['Tripura Bamboo Crafts'].includes(a.name)),
  },
  {
    slug: 'uttarakhand',
    name: 'Uttarakhand',
    description: 'The "Land of the Gods," with sacred rivers, pilgrimage sites, and mountains.',
    imageId: 'state-uttarakhand',
    monuments: monuments.filter(m => ['Badrinath Temple'].includes(m.name)),
    cuisine: cuisine.filter(c => ['Kafuli'].includes(c.name)),
    festivals: festivals.filter(f => ['Kumbh Mela'].includes(f.name)),
    artForms: artForms.filter(a => ['Aipan'].includes(a.name)),
  },
  {
    slug: 'west-bengal',
    name: 'West Bengal',
    description: 'A state renowned for its rich literary, artistic, and intellectual heritage.',
    imageId: 'state-west-bengal',
    monuments: monuments.filter(m => ['Victoria Memorial'].includes(m.name)),
    cuisine: cuisine.filter(c => ['Rasgulla'].includes(c.name)),
    festivals: festivals.filter(f => ['Durga Puja'].includes(f.name)),
    artForms: artForms.filter(a => ['Kantha Embroidery'].includes(a.name)),
  },
];
