
import type { StateData } from './heritage-data';

// Import data for all states
import rajasthanMonuments from './data/rajasthan-monuments.json';
import rajasthanCuisine from './data/rajasthan-cuisine.json';
import rajasthanFestivals from './data/rajasthan-festivals.json';
import rajasthanArt from './data/rajasthan-art.json';

// NOTE: In a real-world scenario, you would create and import JSON files for each state like Rajasthan.
// For this example, we will use smaller, inline datasets for other states for brevity.
// The structure is set up to easily accommodate full JSON files for each.

import { monuments as allMonuments } from './monuments-data';
import { cuisine as allCuisine } from './cuisine-data';
import { festivals as allFestivals } from './festivals-data';
import { artForms as allArtForms } from './art-data';


export const indianStates: StateData[] = [
  {
    slug: 'uttar-pradesh',
    name: 'Uttar Pradesh',
    description: 'The heartland of India, rich in history, culture, and spirituality, home to sacred rivers and ancient cities.',
    imageId: 'state-uttar-pradesh',
    monuments: allMonuments.filter(m => ['Agra Fort', 'Fatehpur Sikri'].includes(m.name)),
    cuisine: allCuisine.filter(c => ['Bedmi Puri', 'Petha'].includes(c.name)),
    festivals: allFestivals.filter(f => ['Diwali', 'Holi', 'Kumbh Mela'].includes(f.name)),
    artForms: allArtForms.filter(a => ['Chikankari'].includes(a.name)),
  },
  {
    slug: 'rajasthan',
    name: 'Rajasthan',
    description: 'The land of kings, majestic forts, vibrant culture, and vast deserts.',
    imageId: 'state-rajasthan',
    monuments: rajasthanMonuments,
    cuisine: rajasthanCuisine,
    festivals: rajasthanFestivals,
    artForms: rajasthanArt,
  },
  {
    slug: 'karnataka',
    name: 'Karnataka',
    description: 'A blend of ancient heritage, modern technology, and stunning natural beauty.',
    imageId: 'state-karnataka',
    monuments: allMonuments.filter(m => ['Mysore Palace', 'Gol Gumbaz', 'Hampi', 'Virupaksha Temple, Hampi'].includes(m.name)),
    cuisine: allCuisine.filter(c => ['Bisi Bele Bath', 'Mysore Pak', 'Masala Dosa'].includes(c.name)),
    festivals: allFestivals.filter(f => ['Dasara', 'Ugadi'].includes(f.name)),
    artForms: allArtForms.filter(a => ['Mysore Painting', 'Bidriware', 'Yakshagana', 'Mysore Rosewood Inlay'].includes(a.name)),
  },
  {
    slug: 'odisha',
    name: 'Odisha',
    description: 'Home to ancient temples, serene beaches, and rich artistic traditions.',
    imageId: 'state-odisha',
    monuments: allMonuments.filter(m => ['Lingaraja Temple', 'Udayagiri Caves', 'Konark Sun Temple'].includes(m.name)),
    cuisine: allCuisine.filter(c => ["Chenna Poda", "Pakhala Bhata"].includes(c.name)),
    festivals: allFestivals.filter(f => ["Ratha Yatra", "Durga Puja"].includes(f.name)),
    artForms: allArtForms.filter(a => ["Pattachitra", 'Odissi Music', 'Pipli Appliqué Work'].includes(a.name)),
  },
  {
    slug: 'andhra-pradesh',
    name: 'Andhra Pradesh',
    description: 'Known for its rich history, spiritual centers, and spicy cuisine.',
    imageId: 'state-andhra-pradesh',
    monuments: allMonuments.filter(m => ['Tirupati'].includes(m.name)),
    cuisine: allCuisine.filter(c => ['Pulihora', 'Pootharekulu'].includes(c.name)),
    festivals: allFestivals.filter(f => ['Ugadi', 'Makar Sankranti'].includes(f.name)),
    artForms: allArtForms.filter(a => ['Kalamkari', 'Kuchipudi', 'Leather Puppetry (Tholu Bommalata)'].includes(a.name)),
  },
  {
    slug: 'arunachal-pradesh',
    name: 'Arunachal Pradesh',
    description: 'The land of the rising sun, with breathtaking mountains and diverse tribes.',
    imageId: 'state-arunachal-pradesh',
    monuments: allMonuments.filter(m => ['Tawang Monastery'].includes(m.name)),
    cuisine: allCuisine.filter(c => ['Thukpa'].includes(c.name)),
    festivals: allFestivals.filter(f => ['Losar'].includes(f.name)),
    artForms: allArtForms.filter(a => ['Apatani Weaving'].includes(a.name)),
  },
  {
    slug: 'assam',
    name: 'Assam',
    description: 'Famous for its tea gardens, rich wildlife, and vibrant culture.',
    imageId: 'state-assam',
    monuments: allMonuments.filter(m => ['Kamakhya Temple'].includes(m.name)),
    cuisine: allCuisine.filter(c => ['Masor Tenga', 'Pitha'].includes(c.name)),
    festivals: allFestivals.filter(f => ['Bihu'].includes(f.name)),
    artForms: allArtForms.filter(a => ['Muga Silk', 'Sattriya'].includes(a.name)),
  },
  {
    slug: 'bihar',
    name: 'Bihar',
    description: 'An ancient land of learning and spirituality, home to major historical sites.',
    imageId: 'state-bihar',
    monuments: allMonuments.filter(m => ['Mahabodhi Temple'].includes(m.name)),
    cuisine: allCuisine.filter(c => ['Litti Chokha', 'Thekua', 'Sohar'].includes(c.name)),
    festivals: allFestivals.filter(f => ['Chhath Puja'].includes(f.name)),
    artForms: allArtForms.filter(a => ['Madhubani Painting'].includes(a.name)),
  },
  {
    slug: 'chhattisgarh',
    name: 'Chhattisgarh',
    description: 'A heavily forested state known for its waterfalls, caves, and tribal culture.',
    imageId: 'state-chhattisgarh',
    monuments: allMonuments.filter(m => ['Chitrakote Falls'].includes(m.name)),
    cuisine: allCuisine.filter(c => ['Faraa'].includes(c.name)),
    festivals: allFestivals.filter(f => ['Bastar Dussehra'].includes(f.name)),
    artForms: allArtForms.filter(a => ['Dhokra', 'Gond Painting', 'Pandavani'].includes(a.name)),
  },
  {
    slug: 'goa',
    name: 'Goa',
    description: 'Famous for its pristine beaches, vibrant nightlife, and Portuguese heritage.',
    imageId: 'state-goa',
    monuments: allMonuments.filter(m => ['Basilica of Bom Jesus'].includes(m.name)),
    cuisine: allCuisine.filter(c => ['Goan Fish Curry'].includes(c.name)),
    festivals: allFestivals.filter(f => ['Goa Carnival', 'Shigmo'].includes(f.name)),
    artForms: allArtForms.filter(a => ['Azulejos'].includes(a.name)),
  },
  {
    slug: 'gujarat',
    name: 'Gujarat',
    description: 'A land of diverse landscapes, from deserts to coastlines, with a rich history.',
    imageId: 'state-gujarat',
    monuments: allMonuments.filter(m => ['Rani ki Vav', 'Adalaj Stepwell'].includes(m.name)),
    cuisine: allCuisine.filter(c => ['Dhokla', 'Undhiyu', 'Puran Poli'].includes(c.name)),
    festivals: allFestivals.filter(f => ['Navaratri', 'Uttarayan', 'Tarnetar Fair'].includes(f.name)),
    artForms: allArtForms.filter(a => ['Bandhani', 'Garba', 'Dandiya Raas'].includes(a.name)),
  },
  {
    slug: 'haryana',
    name: 'Haryana',
    description: 'An agricultural hub with a rich history dating back to the Vedic period.',
    imageId: 'state-haryana',
    monuments: allMonuments.filter(m => ['Kurukshetra'].includes(m.name)),
    cuisine: allCuisine.filter(c => ['Bajra Khichdi'].includes(c.name)),
    festivals: allFestivals.filter(f => ['Gugga Naumi'].includes(f.name)),
    artForms: allArtForms.filter(a => ['Panja Durries'].includes(a.name)),
  },
  {
    slug: 'himachal-pradesh',
    name: 'Himachal Pradesh',
    description: 'A Himalayan paradise with stunning mountain landscapes and adventure sports.',
    imageId: 'state-himachal-pradesh',
    monuments: allMonuments.filter(m => ['Hadimba Temple'].includes(m.name)),
    cuisine: allCuisine.filter(c => ['Dham'].includes(c.name)),
    festivals: allFestivals.filter(f => ['Kullu Dussehra'].includes(f.name)),
    artForms: allArtForms.filter(a => ['Kangra Painting'].includes(a.name)),
  },
  {
    slug: 'jharkhand',
    name: 'Jharkhand',
    description: 'A state rich in mineral wealth, dense forests, and vibrant tribal culture.',
    imageId: 'state-jharkhand',
    monuments: allMonuments.filter(m => ['Baidyanath Temple'].includes(m.name)),
    cuisine: allCuisine.filter(c => ['Dhuska', 'Thekua'].includes(c.name)),
    festivals: allFestivals.filter(f => ['Sarhul'].includes(f.name)),
    artForms: allArtForms.filter(a => ['Sohrai Art', 'Dhokra'].includes(a.name)),
  },
  {
    slug: 'kerala',
    name: 'Kerala',
    description: "God's Own Country, known for its serene backwaters, lush greenery, and rich traditions.",
    imageId: 'hero-kerala-backwaters',
    monuments: allMonuments.filter(m => ['Mattancherry Palace'].includes(m.name)),
    cuisine: allCuisine.filter(c => ['Appam and Stew', 'Idiyappam'].includes(c.name)),
    festivals: allFestivals.filter(f => ['Onam', 'Thrissur Pooram'].includes(f.name)),
    artForms: allArtForms.filter(a => ['Kathakali', 'Theyyam', 'Mohiniyattam'].includes(a.name)),
  },
  {
    slug: 'madhya-pradesh',
    name: 'Madhya Pradesh',
    description: 'The heart of India, with ancient temples, national parks, and rich history.',
    imageId: 'state-madhya-pradesh',
    monuments: allMonuments.filter(m => ['Khajuraho', 'Sanchi Stupa', 'Rock Shelters of Bhimbetka'].includes(m.name)),
    cuisine: allCuisine.filter(c => ['Poha-Jalebi'].includes(c.name)),
    festivals: allFestivals.filter(f => ['Lokrang Festival'].includes(f.name)),
    artForms: allArtForms.filter(a => ['Gond Painting'].includes(a.name)),
  },
  {
    slug: 'maharashtra',
    name: 'Maharashtra',
    description: 'A state of contrasts, from the bustling metropolis of Mumbai to ancient caves.',
    imageId: 'state-maharashtra',
    monuments: allMonuments.filter(m => ['Ajanta & Ellora Caves', 'Gateway of India', 'Shaniwar Wada'].includes(m.name)),
    cuisine: allCuisine.filter(c => ['Vada Pav', 'Puran Poli'].includes(c.name)),
    festivals: allFestivals.filter(f => ['Ganesh Chaturthi'].includes(f.name)),
    artForms: allArtForms.filter(a => ['Warli Painting', 'Lavani', 'Koli Geet', 'Powada'].includes(a.name)),
  },
  {
    slug: 'manipur',
    name: 'Manipur',
    description: 'The jewel of India, known for its classical dance, natural beauty, and sports.',
    imageId: 'state-manipur',
    monuments: allMonuments.filter(m => ['Kangla Fort'].includes(m.name)),
    cuisine: allCuisine.filter(c => ['Eromba'].includes(c.name)),
    festivals: allFestivals.filter(f => ['Sangai Festival', 'Cheiraoba'].includes(f.name)),
    artForms: allArtForms.filter(a => ['Manipuri Dance'].includes(a.name)),
  },
  {
    slug: 'meghalaya',
    name: 'Meghalaya',
    description: 'The abode of clouds, famous for its living root bridges and heavy rainfall.',
    imageId: 'state-meghalaya',
    monuments: allMonuments.filter(m => ['Living Root Bridges'].includes(m.name)),
    cuisine: allCuisine.filter(c => ['Jadoh'].includes(c.name)),
    festivals: allFestivals.filter(f => ['Wangala'].includes(f.name)),
    artForms: allArtForms.filter(a => ['Cane and Bamboo Crafts'].includes(a.name)),
  },
  {
    slug: 'mizoram',
    name: 'Mizoram',
    description: 'A land of rolling hills, vibrant culture, and close-knit communities.',
    imageId: 'state-mizoram',
    monuments: allMonuments.filter(m => ['Vantawng Falls'].includes(m.name)),
    cuisine: allCuisine.filter(c => ['Bai'].includes(c.name)),
    festivals: allFestivals.filter(f => ['Chapchar Kut'].includes(f.name)),
    artForms: allArtForms.filter(a => ['Puan Weaving'].includes(a.name)),
  },
  {
    slug: 'nagaland',
    name: 'Nagaland',
    description: 'A vibrant hill state, home to diverse indigenous tribes and rich traditions.',
    imageId: 'state-nagaland',
    monuments: allMonuments.filter(m => ['Kohima War Cemetery'].includes(m.name)),
    cuisine: allCuisine.filter(c => ['Axone'].includes(c.name)),
    festivals: allFestivals.filter(f => ['Hornbill Festival', 'Sekrenyi Festival', 'Aoleang Festival'].includes(f.name)),
    artForms: allArtForms.filter(a => ['Naga Shawls', 'Zeliang Folk Music'].includes(a.name)),
  },
  {
    slug: 'punjab',
    name: 'Punjab',
    description: 'The land of five rivers, known for its fertile fields and vibrant culture.',
    imageId: 'state-punjab',
    monuments: allMonuments.filter(m => ['Golden Temple'].includes(m.name)),
    cuisine: allCuisine.filter(c => ['Makki di Roti & Sarson da Saag', 'Chole Bhature'].includes(c.name)),
    festivals: allFestivals.filter(f => ['Baisakhi', 'Hola Mohalla'].includes(f.name)),
    artForms: allArtForms.filter(a => ['Phulkari', 'Bhangra', 'Gatka'].includes(a.name)),
  },
  {
    slug: 'sikkim',
    name: 'Sikkim',
    description: 'A Himalayan wonderland with pristine landscapes and Buddhist monasteries.',
    imageId: 'state-sikkim',
    monuments: allMonuments.filter(m => ['Rumtek Monastery'].includes(m.name)),
    cuisine: allCuisine.filter(c => ['Momos', 'Thukpa'].includes(c.name)),
    festivals: allFestivals.filter(f => ['Saga Dawa', 'Losar'].includes(f.name)),
    artForms: allArtForms.filter(a => ['Thangka Painting'].includes(a.name)),
  },
  {
    slug: 'tamil-nadu',
    name: 'Tamil Nadu',
    description: 'A land of towering temples, classical dance, and a rich literary tradition.',
    imageId: 'state-tamil-nadu',
    monuments: allMonuments.filter(m => ['Meenakshi Amman Temple', 'Brihadeeswarar Temple', 'Shore Temple'].includes(m.name)),
    cuisine: allCuisine.filter(c => ['Pongal', 'Idiyappam', 'Chettinad Chicken'].includes(c.name)),
    festivals: allFestivals.filter(f => ['Pongal', 'Panguni Uthiram', 'Chithirai Festival', 'Jallikattu'].includes(f.name)),
    artForms: allArtForms.filter(a => ['Bharatanatyam', 'Kanjivaram Silk Saree', 'Tanjore Painting', 'Kolam', 'Gaana', 'Villu Paatu'].includes(a.name)),
  },
  {
    slug: 'telangana',
    name: 'Telangana',
    description: 'A historic region, home to iconic monuments and a unique Deccan culture.',
    imageId: 'state-telangana',
    monuments: allMonuments.filter(m => ['Charminar', 'Golconda Fort'].includes(m.name)),
    cuisine: allCuisine.filter(c => ['Hyderabadi Biryani', 'Pulihora'].includes(c.name)),
    festivals: allFestivals.filter(f => ['Bathukamma', 'Bonalu'].includes(f.name)),
    artForms: allArtForms.filter(a => ['Bidriware', 'Cheriyal Scroll Painting'].includes(a.name)),
  },
  {
    slug: 'tripura',
    name: 'Tripura',
    description: 'A hilly state with a rich cultural heritage, palaces, and bamboo crafts.',
    imageId: 'state-tripura',
    monuments: allMonuments.filter(m => ['Ujjayanta Palace'].includes(m.name)),
    cuisine: allCuisine.filter(c => ['Chauk'].includes(c.name)),
    festivals: allFestivals.filter(f => ['Kharchi Puja'].includes(f.name)),
    artForms: allArtForms.filter(a => ['Tripura Bamboo Crafts', 'Bamboo and Cane Crafts'].includes(a.name)),
  },
  {
    slug: 'uttarakhand',
    name: 'Uttarakhand',
    description: 'The "Land of the Gods," with sacred rivers, pilgrimage sites, and mountains.',
    imageId: 'state-uttarakhand',
    monuments: allMonuments.filter(m => ['Badrinath Temple'].includes(m.name)),
    cuisine: allCuisine.filter(c => ['Kafuli', 'Bhangjeer ki Chutney'].includes(c.name)),
    festivals: allFestivals.filter(f => ['Kumbh Mela'].includes(f.name)),
    artForms: allArtForms.filter(a => ['Aipan', 'Bowli Geet'].includes(a.name)),
  },
  {
    slug: 'west-bengal',
    name: 'West Bengal',
    description: 'A state renowned for its rich literary, artistic, and intellectual heritage.',
    imageId: 'state-west-bengal',
    monuments: allMonuments.filter(m => ['Victoria Memorial'].includes(m.name)),
    cuisine: allCuisine.filter(c => ['Rasgulla', 'Macher Jhol', 'Shorshe Ilish'].includes(c.name)),
    festivals: allFestivals.filter(f => ['Durga Puja'].includes(f.name)),
    artForms: allArtForms.filter(a => ['Kantha Embroidery', 'Baul Music', 'Terracotta Craft', 'Chhau Dance'].includes(a.name)),
  },
];
